DROP TABLE IF EXISTS AUTHORITIES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS todo;

CREATE TABLE IF NOT EXISTS todo
(
    id          bigint AUTO_INCREMENT PRIMARY KEY,
    owner       VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    completed   BOOLEAN      NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS USERS
(
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    ENABLED  SMALLINT,
    PRIMARY KEY (USERNAME)
);

CREATE TABLE IF NOT EXISTS AUTHORITIES
(
    USERNAME  VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME)
);